doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '8.0'
        charset: UTF8
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        types:
            uuid_db_type: TaskFlow\Shared\Infrastructure\Persistence\Doctrine\DBAL\UuidDbType
            task_priority_db_type: TaskFlow\Core\Task\Infrastructure\Persistence\Doctrine\DBAL\TaskPriorityDbType
            task_status_db_type: TaskFlow\Core\Task\Infrastructure\Persistence\Doctrine\DBAL\TaskStatusDbType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            metric_task:
                mapping: true
                type: xml
                dir: "%kernel.project_dir%/src/Metric/MetricTask/Infrastructure/Persistence/Doctrine"
                prefix: 'TaskFlow\Metric\MetricTask\Domain'
                is_bundle: false

            core_task:
                mapping: true
                type: xml
                dir: "%kernel.project_dir%/src/Core/Task/Infrastructure/Persistence/Doctrine"
                prefix: 'TaskFlow\Core\Task\Domain'
                is_bundle: false

            core_user:
                mapping: true
                type: xml
                dir: "%kernel.project_dir%/src/Core/User/Infrastructure/Persistence/Doctrine"
                prefix: 'TaskFlow\Core\User\Domain'
                is_bundle: false
when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
