version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: top_sport_nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - top_sport_network

  php:
    image: php:8.1-fpm
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: top_sport_app
    volumes:
      - .:/var/www/html
    networks:
      - top_sport_network

  db:
    image: mysql:8.0
    container_name: top_sport_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: core
    ports:
      - "3307:3306"
    networks:
      - top_sport_network

networks:
  top_sport_network:
    driver: bridge