version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: task_flow_nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - task_flow_network

  php:
    image: php:8.1-fpm
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: task_flow_app
    volumes:
      - .:/var/www/html
    networks:
      - task_flow_network

  db:
    image: mysql:8.0
    container_name: task_flow_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: core
    ports:
      - "3307:3306"
    networks:
      - task_flow_network

networks:
  task_flow_network:
    driver: bridge