# Create user
@userId= cd7c8ff8-0066-44a5-bd70-9fa7e25a08ef

POST http://localhost:8080/public/api/users/{{userId}}
Content-Type: application/json

{
  "name": "user test",
  "email":"test@test.com",
  "password":"Password1"
}

###

# Login
POST http://localhost:8080/public/api/login_check
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "Password1"
}
> {%
    client.global.set("token", response.body.token);
%}


###

@firstTaskId = 433774ed-8062-4f18-a743-ec6df03b5e46

# Create a task
POST http://localhost:8080/backoffice/api/tasks/{{firstTaskId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Task home",
 "description": "I need to go to the market"
}

###

@secondTaskId = 433774ed-8062-4f18-a743-ec6df03b5e48

# Create other task
POST http://localhost:8080/backoffice/api/tasks/{{secondTaskId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "call doctor",
  "description": "I have to call the doctor",
  "priority" : "high"
}

###

# Change second task
PUT http://localhost:8080/backoffice/api/tasks/{{secondTaskId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "call doctor",
  "description": "I have to call the doctor",
  "priority" : "critical"
}

###

# Get second task
GET http://localhost:8080/backoffice/api/tasks/{{secondTaskId}}
Content-Type: application/json
Authorization: Bearer {{token}}

###

# List tasks
GET http://localhost:8080/backoffice/api/tasks
Content-Type: application/json
Authorization: Bearer {{token}}

###
# List metric tasks
GET http://localhost:8080/backoffice/api/metric-tasks
Content-Type: application/json
Authorization: Bearer {{token}}

###

# Remove first task
DELETE http://localhost:8080/backoffice/api/tasks/{{firstTaskId}}
Content-Type: application/json
Authorization: Bearer {{token}}

###

# List metric tasks after remove first task
GET http://localhost:8080/backoffice/api/metric-tasks
Content-Type: application/json
Authorization: Bearer {{token}}